name: update

on:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@4bd02057ba6da0db59f49a8daa8c6d2d19bf240a # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
