name: update

on:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@b1ad2a4aa1d05fba8ce5c3590f486546a5c7c0fa # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
