name: update

on:
  schedule:
    - cron: '0 0 * * *' #UTC

jobs:
  composer:
    uses: kawax/composer-workflow/.github/workflows/update.yml@888e53044760bcd5a8dfcb8501ae7d48f58ab10c # v1
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
